name: IUM

on:
  workflow_dispatch:
    inputs:
      epochs:
        description: 'Number of epochs'
        required: true
        default: '5'

jobs:
  data_processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Data Preprocessing
        run: |
          python3 ./preprocess_data.py

      - name: Upload Data Artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: |
            forest_train.csv 
            forest_test.csv
            forest_val.csv

  model_training:
    needs: data_processing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip install pandas scikit-learn torch

      - name: Download Data Artifact
        uses: actions/download-artifact@v4
        with:
          name: data

      - name: Train Model
        run: python3 model.py

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model.pth

  model_evaluation:
    needs: model_training
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pandas torch scikit-learn numpy

      - name: Download Data Artifact
        uses: actions/download-artifact@v4
        with:
          name: data

      - name: Download Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: model

      - name: Evaluate Model
        run: |
          python3 prediction.py

      - name: Upload Evaluation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluation
          path: predictions.txt